### ISSUE TITLE
Gostei! Vou acompanhar, mas... Poderia colocar no ar?

### ISSUE THREAD

**Issue by Coffee-for-Cats** [mari-tza/desafio-100-dias-Js#2]
No Github tem como criar as Github pages, é uma forma simples de se colocar um projetinho assim no ar, sem pagar nada, e fica bem legal para se ver sem precisar usar o Git todo dia.

Outra opção é colocar online pela Vercel, 100% gratúita e com mais possibilidades para o Backend.

Acredito que você consiga fazer facilmente, mas pode entrar em contato comigo se tiver dúvidas, aqui estão meus contatos:
- **Email**: lucas.schwalm.silva@gmail.com
- **Whatsapp**: (51) 9 8117-5622

**Comment by mari-tza** [comment]
Eu sei da existência do GitHub pages e uso em alguns projetos, mas esse dos 100 dias nao tenho interesse em colocar no ar, já que são páginas simples :) Mas agradeço a sugestão
